"""
plot_g1_abs_qerror.py — Q-Error histogram for G1 DuckDB top-143 absolute-headroom queries vs. JOB.

Uses cached cardinality Q-error data from analysis/cardinality_qerror.db and
analysis/job_qerror.db (generated by cardinality_qerror.py and job_qerror.py).
The 143 adversarial queries should already be a subset of the 999 queries measured.

Usage:
    uv run python analysis/plot_g1_abs_qerror.py
"""

import csv
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np

TOP143_CSV = Path(__file__).parent / "g1_duckdb_top143_dedup_by_abs.csv"
ADV_DB = Path(__file__).parent / "cardinality_qerror.db"
JOB_DB = Path(__file__).parent / "job_qerror.db"
OUT_PNG = Path(__file__).parent / "g1_abs_qerror_histogram.png"


def _qerror(true: float, estimated: float) -> float:
    true = max(float(true), 1.0)
    estimated = max(float(estimated), 1.0)
    return max(true / estimated, estimated / true)


def load_top143_queries() -> list[str]:
    with open(TOP143_CSV) as f:
        return [row["query"] for row in csv.DictReader(f)]


def load_adversarial_qerrors(queries: list[str]) -> list[float]:
    placeholders = ",".join(["?"] * len(queries))
    db = sqlite3.connect(str(ADV_DB))
    rows = db.execute(f"""
        SELECT de.result_value, wc.result_value
        FROM cardinality_jobs de
        JOIN cardinality_jobs wc
          ON de.query_dsl = wc.query_dsl AND wc.job_type = 'witness_count'
        WHERE de.job_type = 'default_explain'
          AND de.status = 'complete' AND wc.status = 'complete'
          AND de.query_dsl IN ({placeholders})
    """, queries).fetchall()
    return [_qerror(w_true, de_est) for de_est, w_true in rows]


def load_job_qerrors() -> list[float]:
    db = sqlite3.connect(str(JOB_DB))
    rows = db.execute("""
        SELECT e.result_value, x.result_value
        FROM job_qerror e
        JOIN job_qerror x ON e.query_name = x.query_name AND x.job_type = 'execute'
        WHERE e.job_type = 'explain' AND e.status = 'complete' AND x.status = 'complete'
    """).fetchall()
    return [_qerror(true, est) for est, true in rows]


def plot(adv: list[float], job: list[float]) -> None:
    log_adv = np.log10(adv)
    log_job = np.log10(job)

    xmin = min(log_adv.min(), log_job.min())
    xmax = max(log_adv.max(), log_job.max())
    bins = np.linspace(xmin, xmax, 41)

    x_formatter = ticker.FuncFormatter(
        lambda x, _: f"$10^{{{int(x)}}}$" if x == int(x) else f"$10^{{{x:.1f}}}$"
    )

    plt.rcParams.update({
        "font.size": 18,
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 16,
    })

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.hist(log_adv, bins=bins, alpha=0.7, color="steelblue", edgecolor="white",
            linewidth=0.4, label="G1", density=True)
    ax.hist(log_job, bins=bins, alpha=0.7, color="darkorange", edgecolor="white",
            linewidth=0.4, label="JOB", density=True)
    ax.set_xlabel("Q-Error (log₁₀ scale)")
    ax.set_ylabel("Density")
    ax.xaxis.set_major_formatter(x_formatter)
    ax.legend()
    ax.grid(True, axis="y", alpha=0.3)
    ax.set_axisbelow(True)
    fig.tight_layout()

    fig.savefig(OUT_PNG, dpi=300, bbox_inches="tight")
    print(f"Saved to {OUT_PNG}")
    plt.show()


if __name__ == "__main__":
    queries = load_top143_queries()
    print(f"Loaded {len(queries)} queries from CSV ({len(set(queries))} unique)")

    adv = load_adversarial_qerrors(queries)
    job = load_job_qerrors()

    for label, qerrors in [("G1 abs top-143", adv), ("JOB", job)]:
        print(f"{label} ({len(qerrors)} queries):")
        print(f"  Median:  {np.median(qerrors):.1f}x")
        print(f"  p90:     {np.percentile(qerrors, 90):.1f}x")
        print(f"  Max:     {max(qerrors):.1f}x")

    plot(adv, job)
